service: aws-sls-s3-trigger-test

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  ecr:
    images:
      lambdagrader-image:
        path: ./
  environment:
    JUPYTER_NOTEBOOK_SUBMISSION_BUCKET: "serverless-jupyter-notebook-submission-bucket"
    JUPYTER_NOTEBOOK_GRADED_BUCKET: "serverless-jupyter-notebook-graded-bucket"
    REGION_NAME: "us-east-1"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  hello:
    handler: handler.hello
  grade_S3_uploaded_notebook:
    image:
      name: lambdagrader-image
    events:
      - s3:
          bucket: ${self:provider.environment.JUPYTER_NOTEBOOK_SUBMISSION_BUCKET}
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - suffix: .ipynb
    memorySize: 4096 # 4 GB to run Jupyter notebooks
    timeout: 900 # 15 minutes timeout
