service: aws-sls-s3-trigger-test

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  ecr:
    images:
      appimage:
        path: ./
  environment:
    JUPYTER_NOTEBOOK_SUBMISSION_BUCKET: "serverless-jupyter-notebook-submission-bucket"
    REGION_NAME: "us-east-1"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  hello:
    handler: handler.hello
  handleS3Upload:
    handler: handler.handleS3Upload
    events:
      - s3:
          bucket: ${self:provider.environment.JUPYTER_NOTEBOOK_SUBMISSION_BUCKET}
          event: s3:ObjectCreated:*
          existing: true
  get_tomatoes:
    image:
      name: appimage
